### ISSUE TITLE
Add Javascript Support

### ISSUE THREAD

**Issue by Lonniebiz** [umbopepato/velociraptor#30]
Instead of JSON and YAML, I'd prefer to use a JavaScript module. For example, instead of this JSON:
```
{
  "scripts": {
    "start": "deno run --allow-net server.ts",
    "test": "deno test --allow-net server_test.ts"
  }
}
```
or this YAML:
```
# scripts.yaml
scripts:
  start: deno run --allow-net server.ts
  test: deno test --allow-net server_test.ts
```

I prefer this:
```
let options = {};
options.scripts = {};
options.scripts.start = "deno run --allow-net server.ts";
options.scripts.test = "deno test --allow-net server_test.ts";
export options;
```
Granted, my preference is more verbose. However, nothing is more flexible. You could do anything you wanted (programmatically) within this file and Velociraptor should only care about the object that gets exported at the end.
